name: cargo test report
author: Gary Tierney
description: Create JUnit reports from Cargo tests (nightly only)
branding:
  icon: activity
  color: green

inputs:
  cargo-opts:
    description: Command-line arguments forwarded to Cargo
    required: false
    default: "--all"
  test-command:
    description: The cargo sub-command to execute tests using (i.e. "miri test")
    required: false
    default: "test"
  test-opts:
    description: Command-line arguments forwarded to libtest
    required: false
    default: "-Z unstable-options --show-output"
  test-prefix:
    description: Prefix added to test-reports, use to disambiguate with other test runs
    required: false
    default: "test"
runs:
  using: composite
  steps:
    - id: run
      name: Run tests
      run: |
        test_counter=0
        cargo "${TEST_COMMAND[@]}" "${CARGO_OPTS[@]}" -- -Z unstable-options "${TEST_OPTS[@]}" --format=junit |
        while IFS="\n" read -r line; do
          file="./target/$TEST_PREFIX-$test_counter.xml"
        
          echo "$line" > "$file"
          echo "Report written to $file"
        
          ((test_counter=test_counter+1))
        done
      env:
        CARGO_OPTS: ${{ inputs.cargo-opts }}
        TEST_COMMAND: ${{ inputs.test-command }}
        TEST_OPTS: ${{ inputs.test-opts }}
        TEST_PREFIX: ${{ inputs.test-prefix }}
      shell: bash